### ISSUE TITLE
fontName

### ISSUE THREAD

**Issue by lJohhnyl** [THE-FYP/SAMP.Lua#3]
При использовании **fontName** из [read_object_material_text](https://github.com/THE-FYP/SAMP.Lua/blob/master/samp/events/handlers.lua#L449) выдает ошибочный шрифт. 
Вместо "Arial" мы получаем "Ariel".
Пример:
```SetObjectMaterialText(980,'ПРЕСС-ЦЕНТР',0,130,Ariel,30,1,-16777216,0);```

**Comment by THE-FYP** [comment]
скорее всего это ошибка в самом моде/скрипте сервера.

**Comment by THE-FYP** [comment]
@lJohhnyl проблема решена?
